### ISSUE TITLE
Collision issue on tunnel

### ISSUE THREAD

**Issue by trisutrisnowapu** [XrunMeta/CLUBX#104]
There is a collision issue in tunnel mnext to the second floor after the elevator @opikropikin please check it out

**Comment by opikropikin** [comment]
oh okey mr.tri i check, maybe iam change tje collision and add  collision box in tunnel area

**Comment by opikropikin** [comment]
![collision](https://github.com/XrunMeta/CLUBX/assets/123038142/531bbee5-b437-49fc-8c42-3b877fc4d772)

for misssing collision done update . . .

**Comment by trisutrisnowapu** [comment]
Awesome, don't forget to submit to perforce
